-- Le schéma exécutable et versionné se trouve dans :
-- supabase/migrations/20260825190000_initial_secure_schema.sql
--
-- Utiliser `supabase db push` ou copier cette migration dans le SQL Editor
-- du projet cible. Ne pas maintenir une seconde copie divergente ici.
